
unit DeviceServiceManager_novo;

interface

uses
  Androidapi.JNI.JavaTypes, 
  Androidapi.JNI.GraphicsContentViewText, 
  Androidapi.JNI.Os, 
  Androidapi.Helpers,
  DeviceSDK;  // The unit generated by java2op for handling the SDK bridge

type
  TDeviceServiceManager = class
  private
    FDeviceService: JAidlDeviceService;
    function GetService(const ServiceName: JString): JIBinder;
    procedure BindDeviceService;
  public
    function GetPrintManager: JAidlPrinter;
    function GetSystemManager: JAidlSystem;
    function GetCameraManager: JAidlCameraScanCode;
    constructor Create;
  end;

implementation

constructor TDeviceServiceManager.Create;
begin
  // Binding the device service during instantiation
  BindDeviceService;
end;

procedure TDeviceServiceManager.BindDeviceService;
var
  Intent: JIntent;
begin
  Intent := TJIntent.JavaClass.init;
  Intent.setAction(StringToJString('topwise_cloudpos_device_service'));
  Intent.setClassName(StringToJString('com.android.topwise.topusdkservice'),
    StringToJString('com.android.topwise.topusdkservice.service.DeviceService'));

  TAndroidHelper.Context.bindService(Intent, nil, TJContext.JavaClass.BIND_AUTO_CREATE);
end;

function TDeviceServiceManager.GetService(const ServiceName: JString): JIBinder;
var
  ServiceManager: JObject;
  Method: JMethod;
  Binder: JIBinder;
begin
  ServiceManager := TJServiceManager.JavaClass.getService(ServiceName);
  Method := ServiceManager.getClass.getMethod('getService', TJavaObjectArray<JClass>.Create);
  Binder := TJBinder.Wrap(Method.invoke(ServiceManager, [ServiceName]));
  Result := Binder;
end;

function TDeviceServiceManager.GetPrintManager: JAidlPrinter;
begin
  if FDeviceService <> nil then
    Result := FDeviceService.getPrinter;
end;

function TDeviceServiceManager.GetSystemManager: JAidlSystem;
begin
  if FDeviceService <> nil then
    Result := FDeviceService.getSystemService;
end;

function TDeviceServiceManager.GetCameraManager: JAidlCameraScanCode;
begin
  if FDeviceService <> nil then
    Result := FDeviceService.getCameraManager;
end;

end.
